apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-config-map
  namespace: spring-microservice-ns
data:
  SERVER_PORT: "8888"
  SPRING_APPLICATION_NAME: "config-server"
  SPRING_CLOUD_CONFIG_SERVER_GIT_URI: "https://github.com/plats-spring-microservices/spring-configuration"
  SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH_PATHS: "{application}"